confio/poe-contracts

Cargo.lock
contracts/tg4-engagement/Cargo.toml
contracts/tg4-mixer/Cargo.toml
contracts/tg4-stake/Cargo.toml
contracts/tgrade-community-pool/Cargo.toml
contracts/tgrade-gov-reflect/Cargo.toml
contracts/tgrade-validator-voting/Cargo.toml
contracts/tgrade-valset/Cargo.toml
contracts/tgrade-vesting-account/Cargo.toml
packages/bindings-test/Cargo.toml
packages/bindings/Cargo.toml
packages/tg4/Cargo.toml
packages/utils/Cargo.toml
packages/voting-contract/Cargo.toml
scripts/publish.sh

Add publish script and add license to Cargo.toml files

---

contracts/tgrade-valset/src/msg.rs
packages/utils/src/jailing.rs

closes https://github.com/confio/poe-contracts/issues/20
@ethanfrey is that what you meant with using same JSON format in both cases?

Valset: Fix JailMsg inconsistencies

---

.circleci/config.yml

Update rust to v0.44.0 in CI

---

contracts/tgrade-validator-voting/src/contract.rs
contracts/tgrade-validator-voting/src/error.rs
contracts/tgrade-validator-voting/src/multitest.rs
contracts/tgrade-validator-voting/src/multitest/suite.rs

closes https://github.com/confio/poe-contracts/issues/46

ValidatorVoting - make sure proposal migrate msg is not empty

---

packages/tg4/src/helpers.rs

Similar fix than for https://github.com/CosmWasm/cw-plus/issues/637.

Fix `remove_hook` helper

---

Cargo.lock
contracts/tg4-engagement/Cargo.toml
contracts/tg4-mixer/Cargo.toml
contracts/tg4-stake/Cargo.toml
contracts/tgrade-community-pool/Cargo.toml
contracts/tgrade-gov-reflect/Cargo.toml
contracts/tgrade-validator-voting/Cargo.toml
contracts/tgrade-valset/Cargo.toml
contracts/tgrade-vesting-account/Cargo.toml
packages/bindings-test/Cargo.toml
packages/bindings/Cargo.toml
packages/test-utils/Cargo.toml
packages/tg4/Cargo.toml
packages/utils/Cargo.toml
packages/voting-contract/Cargo.toml

Need a new release of `voting-contract` to implement open text proposals in tgrade.

0.6.0-alpha1 release

---

contracts/tgrade-community-pool/src/contract.rs
contracts/tgrade-community-pool/src/msg.rs
contracts/tgrade-validator-voting/src/contract.rs
contracts/tgrade-validator-voting/src/msg.rs
packages/voting-contract/src/lib.rs
packages/voting-contract/src/msg.rs
packages/voting-contract/src/multitest/contracts/voting.rs
packages/voting-contract/src/multitest/queries.rs
packages/voting-contract/src/multitest/suite.rs
packages/voting-contract/src/state.rs

closes https://github.com/confio/poe-contracts/issues/78

Voting Contract: Add list_votes_by_voter query

---

CHANGELOG.md
Cargo.lock
MIGRATING.md
contracts/tg4-engagement/Cargo.toml
contracts/tg4-mixer/Cargo.toml
contracts/tg4-stake/Cargo.toml
contracts/tgrade-community-pool/Cargo.toml
contracts/tgrade-gov-reflect/Cargo.toml
contracts/tgrade-validator-voting/Cargo.toml
contracts/tgrade-valset/Cargo.toml
contracts/tgrade-vesting-account/Cargo.toml
packages/bindings-test/Cargo.toml
packages/bindings/Cargo.toml
packages/test-utils/Cargo.toml
packages/tg4/Cargo.toml
packages/utils/Cargo.toml
packages/voting-contract/Cargo.toml

closes https://github.com/confio/poe-contracts/issues/88

Release 0.6.0-rc1

---

scripts/publish.sh

follow up of https://github.com/confio/poe-contracts/pull/97

Fix typo in publish.sh script

---

Cargo.lock
contracts/tgrade-community-pool/Cargo.toml
contracts/tgrade-validator-voting/Cargo.toml
packages/tg3/Cargo.toml
packages/voting-contract/Cargo.toml

Done by hand - this should do the trick, right?

tg3: align version

---

CHANGELOG.md
Cargo.lock
contracts/tg4-engagement/Cargo.toml
contracts/tg4-group/Cargo.toml
contracts/tg4-mixer/Cargo.toml
contracts/tg4-stake/Cargo.toml
contracts/tgrade-community-pool/Cargo.toml
contracts/tgrade-gov-reflect/Cargo.toml
contracts/tgrade-validator-voting/Cargo.toml
contracts/tgrade-valset/Cargo.toml
contracts/tgrade-vesting-account/Cargo.toml
packages/bindings-test/Cargo.toml
packages/bindings/Cargo.toml
packages/test-utils/Cargo.toml
packages/tg3/Cargo.toml
packages/tg4/Cargo.toml
packages/utils/Cargo.toml
packages/voting-contract/Cargo.toml

So that we can release `tg4-group`.

Release 0.6.1

---

CHANGELOG.md
Cargo.lock
contracts/tg4-engagement/Cargo.toml
contracts/tg4-group/Cargo.toml
contracts/tg4-mixer/Cargo.toml
contracts/tg4-stake/Cargo.toml
contracts/tgrade-community-pool/Cargo.toml
contracts/tgrade-gov-reflect/Cargo.toml
contracts/tgrade-validator-voting/Cargo.toml
contracts/tgrade-valset/Cargo.toml
contracts/tgrade-vesting-account/Cargo.toml
packages/bindings-test/Cargo.toml
packages/bindings/Cargo.toml
packages/test-utils/Cargo.toml
packages/tg3/Cargo.toml
packages/tg4/Cargo.toml
packages/utils/Cargo.toml
packages/voting-contract/Cargo.toml

To release a new `tg4-group` contract, after #109.

Release 0.6.2

---

Cargo.lock
contracts/tgrade-valset/Cargo.toml
contracts/tgrade-valset/src/contract.rs
contracts/tgrade-valset/src/lib.rs
contracts/tgrade-valset/src/migration.rs
contracts/tgrade-valset/src/msg.rs
contracts/tgrade-valset/src/multitest/double_sign.rs
contracts/tgrade-valset/src/multitest/helpers.rs
contracts/tgrade-valset/src/multitest/jailing.rs

Closes #94
Working on migration code for this.

valset: store and expose the start of a jailing period

---

CHANGELOG.md
Cargo.lock
contracts/tg4-engagement/Cargo.toml
contracts/tg4-group/Cargo.toml
contracts/tg4-mixer/Cargo.toml
contracts/tg4-stake/Cargo.toml
contracts/tgrade-community-pool/Cargo.toml
contracts/tgrade-gov-reflect/Cargo.toml
contracts/tgrade-validator-voting/Cargo.toml
contracts/tgrade-valset/Cargo.toml
contracts/tgrade-vesting-account/Cargo.toml
packages/bindings-test/Cargo.toml
packages/bindings/Cargo.toml
packages/test-utils/Cargo.toml
packages/tg3/Cargo.toml
packages/tg4/Cargo.toml
packages/utils/Cargo.toml
packages/voting-contract/Cargo.toml

Release 0.7.0-alpha1

---

CHANGELOG.md
Cargo.lock
contracts/tg4-engagement/Cargo.toml
contracts/tg4-group/Cargo.toml
contracts/tg4-mixer/Cargo.toml
contracts/tg4-stake/Cargo.toml
contracts/tgrade-community-pool/Cargo.toml
contracts/tgrade-gov-reflect/Cargo.toml
contracts/tgrade-validator-voting/Cargo.toml
contracts/tgrade-valset/Cargo.toml
contracts/tgrade-vesting-account/Cargo.toml
packages/bindings-test/Cargo.toml
packages/bindings/Cargo.toml
packages/test-utils/Cargo.toml
packages/tg3/Cargo.toml
packages/tg4/Cargo.toml
packages/utils/Cargo.toml
packages/voting-contract/Cargo.toml
packages/voting-contract/src/lib.rs

New quick release just to make error and ballots from voting contract public.

Release 0.7.0-alpha2

---

.circleci/config.yml
scripts/publish.sh

For proper "edition2021" rust version.

CI update rust optimiser

---

contracts/tgrade-valset/src/multitest/export_import.rs
contracts/tgrade-valset/src/state.rs

Add missing Admin to state export / import

---

contracts/tgrade-validator-voting/src/contract.rs
contracts/tgrade-validator-voting/src/msg.rs

Related / closes part of #158.
Implements the `ChangeParams` proposal type.
TODO:
- ~~Unit tests.~~ (done)

Implement the ChangeParams proposal

---

contracts/tg4-mixer/src/contract.rs
contracts/tg4-mixer/src/error.rs
contracts/tg4-mixer/src/functions.rs
contracts/tg4-stake/src/contract.rs
contracts/tgrade-validator-voting/src/msg.rs
contracts/tgrade-valset/src/contract.rs
contracts/tgrade-valset/src/msg.rs
contracts/tgrade-valset/src/state.rs

Just some housekeeping. Closes #138.

TODO / FIXME review

---

contracts/tg4-stake/src/contract.rs

Related to / closes https://github.com/CosmWasm/cosmwasm/issues/1359.

Remove / replace coins_to_string helper

---

contracts/tg4-mixer/benches/main.rs

Just keeping these values updated, for housekeeping.

Update mixer benchmark gas values

---

contracts/tg4-stake/src/contract.rs
contracts/tg4-stake/src/error.rs

Fix zero amounts during unbound and release

---

LICENSE
LICENSE.txt
NOTICE

Replace closed source license with Apache 2.0
