confio/poe-contracts

packages/bindings-test/src/multitest.rs

It is "cherry-pick" of change created on tgrade repo, original change in two commits:
https://github.com/confio/tgrade-contracts/commit/139a6fb594c697604f44ccce23b48282f1e33bb0#diff-b7f922709abc3226bf11bbb02ae0883d4fa291169e0135fa5b06dfd7af8c3cdb
https://github.com/confio/tgrade-contracts/commit/4610afb04965ff604774251e1880ac94861810db#diff-b7f922709abc3226bf11bbb02ae0883d4fa291169e0135fa5b06dfd7af8c3cdb

bindings-test: added missing genesis constructor

---

Cargo.lock
contracts/tg4-engagement/src/contract.rs
contracts/tg4-mixer/src/contract.rs
contracts/tg4-stake/src/contract.rs
contracts/tgrade-community-pool/Cargo.toml
contracts/tgrade-community-pool/src/contract.rs
contracts/tgrade-validator-voting/Cargo.toml
contracts/tgrade-validator-voting/src/contract.rs
contracts/tgrade-valset/src/contract.rs
packages/bindings/src/query.rs
packages/utils/Cargo.toml
packages/utils/src/lib.rs
packages/utils/src/migrate.rs

Expose migrations in all poe-contracts.
Perform a standardised sanity check that we are migrating the same contract type and an equal or newer version

Allow migrations

---

CHANGELOG.md
Cargo.lock
contracts/tg4-engagement/Cargo.toml
contracts/tg4-mixer/Cargo.toml
contracts/tg4-stake/Cargo.toml
contracts/tgrade-community-pool/Cargo.toml
contracts/tgrade-gov-reflect/Cargo.toml
contracts/tgrade-validator-voting/Cargo.toml
contracts/tgrade-valset/Cargo.toml
contracts/tgrade-vesting-account/Cargo.toml
packages/bindings-test/Cargo.toml
packages/bindings/Cargo.toml
packages/test-utils/Cargo.toml
packages/tg4/Cargo.toml
packages/utils/Cargo.toml
packages/voting-contract/Cargo.toml

After #29 
Prepare to release 0.5.4, so we can tag images and deploy them to migration

Set version: 0.5.4

---

contracts/tgrade-valset/src/contract.rs
contracts/tgrade-valset/src/msg.rs
contracts/tgrade-valset/src/multitest.rs
contracts/tgrade-valset/src/multitest/migration.rs
contracts/tgrade-valset/src/multitest/suite.rs
contracts/tgrade-valset/src/multitest/update_config.rs

Closes #28 
Two ways to update `min_weight` and `max_validators` - by migration or by using an `ExecuteMsg` entrypoint.

valset: Add a feature to update `min_weight` and `max_validators`

---

contracts/tgrade-valset/src/contract.rs
contracts/tgrade-valset/src/msg.rs
contracts/tgrade-valset/src/multitest/jailing.rs
contracts/tgrade-valset/src/state.rs

Closes #23
Waiting for confirmation from @alpe that this is what he wanted before moving this out of draft.

Store information about operators' validator status

---

contracts/tgrade-valset/src/contract.rs
contracts/tgrade-valset/src/msg.rs
contracts/tgrade-valset/src/multitest/contract.rs
contracts/tgrade-valset/src/multitest/jailing.rs
contracts/tgrade-valset/src/multitest/stake.rs
contracts/tgrade-valset/src/multitest/suite.rs

Closes #33. Quick and dirty solution (linear search over the validator set, to simulate `start_after`).

Validator set query pagination

---

.circleci/config.yml

To fix current CI failures:
https://app.circleci.com/pipelines/github/confio/poe-contracts/153/workflows/1570fcfa-349d-4fcc-9820-ff2338401711/jobs/2330

Update rust toolchain to v1.58.1

---

CHANGELOG.md
Cargo.lock
contracts/tg4-engagement/Cargo.toml
contracts/tg4-mixer/Cargo.toml
contracts/tg4-stake/Cargo.toml
contracts/tgrade-community-pool/Cargo.toml
contracts/tgrade-gov-reflect/Cargo.toml
contracts/tgrade-validator-voting/Cargo.toml
contracts/tgrade-valset/Cargo.toml
contracts/tgrade-vesting-account/Cargo.toml
packages/bindings-test/Cargo.toml
packages/bindings/Cargo.toml
packages/test-utils/Cargo.toml
packages/tg4/Cargo.toml
packages/utils/Cargo.toml
packages/voting-contract/Cargo.toml

Closes #67.
For reference, unified diff of schemas between v0.5.5 and this version:
[schema_diffs-v0.5.5-v0.6.0-beta1.txt](https://github.com/confio/poe-contracts/files/7994478/schema_diffs-v0.5.5-v0.6.0-beta1.txt)

Release v0.6.0-beta1

---

contracts/tg4-engagement/src/contract.rs
contracts/tg4-mixer/src/contract.rs
contracts/tg4-stake/src/claim.rs
contracts/tg4-stake/src/contract.rs
contracts/tgrade-community-pool/src/contract.rs
contracts/tgrade-validator-voting/src/contract.rs
contracts/tgrade-valset/src/contract.rs

closes https://github.com/confio/poe-contracts/issues/76

Increase MAX_LIMIT constant to 100 and DEFAULT_LIMIT to 30

---

contracts/tgrade-valset/src/contract.rs
contracts/tgrade-valset/src/error.rs
contracts/tgrade-valset/src/msg.rs
contracts/tgrade-valset/src/multitest/contract.rs
contracts/tgrade-valset/src/multitest/double_sign.rs
contracts/tgrade-valset/src/multitest/helpers.rs
contracts/tgrade-valset/src/multitest/suite.rs
contracts/tgrade-valset/tests/integration.rs

closes https://github.com/confio/poe-contracts/issues/66
In `msg.rs` file I only expanded `ValidatorMetadata::validate()` method and added two more consts. Rest of changes is shuffling some stuff up or down, so for example `QueryMsg` is directly under `InstantiateMsg` enums, instead somewhere in the middle of the file...

Valset: metadata validation

---

contracts/tgrade-valset/src/contract.rs
contracts/tgrade-valset/src/error.rs
contracts/tgrade-valset/src/msg.rs
contracts/tgrade-valset/src/multitest/jailing.rs
contracts/tgrade-valset/src/multitest/suite.rs

closes https://github.com/confio/poe-contracts/issues/87

Valset: Implement ListJailedValidators query

---

contracts/tgrade-valset/README.md
contracts/tgrade-valset/src/contract.rs
contracts/tgrade-valset/src/msg.rs
contracts/tgrade-valset/src/multitest/contract.rs
contracts/tgrade-valset/src/multitest/stake.rs
contracts/tgrade-valset/src/multitest/suite.rs
contracts/tgrade-valset/src/rewards.rs
contracts/tgrade-valset/src/state.rs
contracts/tgrade-valset/src/test_valset_stake.rs

Closes https://github.com/confio/tgrade-contracts/issues/320.
The full renames are:
- `rewards_contract` -> `validator_group`.
- `rewards_code_id` -> `validator_group_code_id` (for consistency).

Valset config contract names

---

CHANGELOG.md
Cargo.lock
MIGRATING.md
contracts/tg4-engagement/Cargo.toml
contracts/tg4-mixer/Cargo.toml
contracts/tg4-stake/Cargo.toml
contracts/tgrade-community-pool/Cargo.toml
contracts/tgrade-gov-reflect/Cargo.toml
contracts/tgrade-validator-voting/Cargo.toml
contracts/tgrade-validator-voting/src/contract.rs
contracts/tgrade-valset/Cargo.toml
contracts/tgrade-vesting-account/Cargo.toml
packages/bindings-test/Cargo.toml
packages/bindings/Cargo.toml
packages/test-utils/Cargo.toml
packages/tg4/Cargo.toml
packages/utils/Cargo.toml
packages/voting-contract/Cargo.toml
packages/voting-contract/src/lib.rs
packages/voting-contract/src/msg.rs
packages/voting-contract/src/multitest/proposing.rs
packages/voting-contract/src/multitest/queries.rs
packages/voting-contract/src/multitest/suite.rs
packages/voting-contract/src/state.rs

Since cw3 was replaced with local tg3, I could easily remove extra `VoteInfo` implementation that is required in tgrade-contracts.
So this new-extra release will make update in tgrade much easier.
Plus extra naming fixes.

Release 0.6.0-rc2

---

.circleci/config.yml
Cargo.lock
contracts/tg4-group/.cargo/config
contracts/tg4-group/Cargo.toml
contracts/tg4-group/NOTICE
contracts/tg4-group/README.md
contracts/tg4-group/examples/schema.rs
contracts/tg4-group/src/contract.rs
contracts/tg4-group/src/error.rs
contracts/tg4-group/src/helpers.rs
contracts/tg4-group/src/lib.rs
contracts/tg4-group/src/msg.rs
contracts/tg4-group/src/state.rs
scripts/publish.sh

Based on `cw4-group`. Adapted to `tgrade-bindings` (`TgradeMsg`), and `tgrade-utils` hooks.
~~Publishing as Draft, as tests are still failing.~~ (fixed)

Add `tg4-group` contract

---

Cargo.lock
contracts/tg4-group/Cargo.toml
contracts/tg4-group/src/contract.rs
contracts/tg4-group/src/error.rs
contracts/tg4-group/src/state.rs

By using `cw4::MemberChangedHookResponse` and  `cw4::MemberDiff` instead of their tgrade counterparts, we can easily "decustomize" this entire contract.

Decustomize `tg4-group`

---

packages/bindings-test/src/multitest.rs

This seems to have failed in some test case (not automatic from Deref)
Explicitly implement Querier to ensure it

Implement Querier for TgradeApp

---

contracts/tgrade-gov-reflect/Cargo.toml

Without it contract's wouldn't publish (and didn't so far).

Add description to tgrade-gov-reflect's Cargo.toml

---

Cargo.lock
contracts/tg4-engagement/Cargo.toml
contracts/tg4-group/Cargo.toml
contracts/tg4-mixer/Cargo.toml
contracts/tg4-stake/Cargo.toml
contracts/tgrade-community-pool/Cargo.toml
contracts/tgrade-gov-reflect/Cargo.toml
contracts/tgrade-validator-voting/Cargo.toml
contracts/tgrade-valset/Cargo.toml
contracts/tgrade-vesting-account/Cargo.toml
packages/bindings-test/Cargo.toml
packages/bindings/Cargo.toml
packages/test-utils/Cargo.toml
packages/tg3/Cargo.toml
packages/tg4/Cargo.toml
packages/utils/Cargo.toml
packages/voting-contract/Cargo.toml

Just to allow trade-validator-voting to update the tfi contracts, which were instantiated with no migration admin.

Release 0.6.2-patch1

---

contracts/tg4-mixer/src/contract.rs
contracts/tg4-stake/src/contract.rs
contracts/tg4-stake/src/msg.rs
contracts/tg4-stake/src/state.rs
contracts/tgrade-valset/src/multitest/suite.rs
packages/bindings-test/src/multitest.rs
packages/bindings/src/hooks.rs
packages/bindings/src/msg.rs

This is the contract side of https://github.com/confio/tgrade/issues/220.
TODO:

Stake vesting accounts

---

CHANGELOG.md
Cargo.lock
contracts/tg4-engagement/Cargo.toml
contracts/tg4-group/Cargo.toml
contracts/tg4-mixer/Cargo.toml
contracts/tg4-stake/Cargo.toml
contracts/tgrade-community-pool/Cargo.toml
contracts/tgrade-gov-reflect/Cargo.toml
contracts/tgrade-validator-voting/Cargo.toml
contracts/tgrade-valset/Cargo.toml
contracts/tgrade-vesting-account/Cargo.toml
packages/bindings-test/Cargo.toml
packages/bindings/Cargo.toml
packages/test-utils/Cargo.toml
packages/tg3/Cargo.toml
packages/tg4/Cargo.toml
packages/utils/Cargo.toml
packages/voting-contract/Cargo.toml
scripts/set_version.sh
scripts/update_changelog.sh

v0.8.0 release. To be used for upcoming internal-10 and dryrunnet testnets.
Just synched `update_changelog.sh` with the version in cw-plus in passing.
Added notice about required `getopt` version for Mac.

Release v0.8.0

---

contracts/tgrade-valset/src/contract.rs
contracts/tgrade-valset/src/msg.rs
contracts/tgrade-valset/src/multitest.rs
contracts/tgrade-valset/src/multitest/contract.rs
contracts/tgrade-valset/src/multitest/stake.rs
contracts/tgrade-valset/src/multitest/suite.rs
contracts/tgrade-valset/src/multitest/verify_online.rs
contracts/tgrade-valset/src/state.rs

Closes #36
At an epoch boundary, any newly added validators are marked as PENDING and their voting power is set to the minimum. Next epoch, these PENDING validators have to have signed the last block or they're jailed for a configurable period. If they do sign it, they get the full voting power.
Two new fields in the instantiation msg:
```rust
/// When a validator joins the valset, verify they sign the first block since joining
/// or jail them for a period otherwise.
///
/// The verification happens every time the validator becomes an active validator,
/// including when they are unjailed or when they just gain enough power to participate.
pub verify_validators: bool,
/// The duration to jail a validator for in case they don't sign their first epoch
/// boundary block. After the period, …
```

Verify new validators are online

---

contracts/tg4-engagement/src/contract.rs
contracts/tg4-engagement/src/msg.rs
contracts/tg4-engagement/src/multitest.rs
contracts/tg4-engagement/src/multitest/suite.rs
contracts/tg4-group/src/contract.rs
contracts/tg4-mixer/src/contract.rs
contracts/tg4-mixer/src/lib.rs
contracts/tg4-mixer/src/member_indexes.rs
contracts/tg4-stake/src/contract.rs
contracts/tgrade-community-pool/src/multitest/suite.rs
contracts/tgrade-validator-voting/src/multitest/suite.rs
contracts/tgrade-valset/src/contract.rs
contracts/tgrade-valset/src/multitest/suite.rs
packages/tg4/src/helpers.rs
packages/tg4/src/lib.rs
packages/tg4/src/query.rs
packages/utils/src/member_indexes.rs
packages/voting-contract/src/lib.rs
packages/voting-contract/src/multitest/suite.rs

Third attempt at closing #22. Follows the plan outlined in https://github.com/confio/poe-contracts/issues/22#issuecomment-1046852028.
TODO:
-  ~~Removing (or not) the optional `start_height` from `MemberResponse`, for simplicity.~~ (not removing)

Valset tie-breaking #3

---

contracts/tgrade-valset/src/multitest/verify_online.rs

Just an extra test, to document offline validators behaviour with auto-unjail.

[tgrade-valset] Offline validator auto-unjail tests

---

CHANGELOG.md
Cargo.lock
contracts/tg4-engagement/Cargo.toml
contracts/tg4-engagement/src/contract.rs
contracts/tg4-group/Cargo.toml
contracts/tg4-group/README.md
contracts/tg4-group/src/contract.rs
contracts/tg4-group/src/state.rs
contracts/tg4-mixer/Cargo.toml
contracts/tg4-stake/Cargo.toml
contracts/tgrade-community-pool/Cargo.toml
contracts/tgrade-gov-reflect/Cargo.toml
contracts/tgrade-validator-voting/Cargo.toml
contracts/tgrade-valset/Cargo.toml
contracts/tgrade-valset/src/multitest/export_import.rs
contracts/tgrade-valset/src/multitest/suite.rs
contracts/tgrade-vesting-account/Cargo.toml
packages/bindings-test/Cargo.toml
packages/bindings/Cargo.toml
packages/test-utils/Cargo.toml
packages/tg3/Cargo.toml
packages/tg4/Cargo.toml
packages/tg4/README.md
packages/tg4/src/helpers.rs
packages/utils/Cargo.toml
packages/voting-contract/Cargo.toml

In order to use `Tg4Contract::is_member`, the member information must be `MemberInfo`. Adapt this contract to the `tg4` standard, so that it can be properly (raw) queried for membership.
Also adapt some tests in tg4-engagement and the `is_member` query comments for clarity.

tg4-group tg4 standard

---

.circleci/config.yml
contracts/tg4-stake/src/contract.rs
contracts/tg4-stake/src/msg.rs

Remove denom from the `TotalPoints` query

---

contracts/tg4-mixer/benches/main.rs
contracts/tg4-mixer/src/contract.rs
contracts/tg4-mixer/src/functions.rs
contracts/tg4-mixer/src/msg.rs

Just so that it aligns better with the current naming for engagement points.

Rename rewards to points in mixer

---

contracts/tg4-mixer/Cargo.toml
contracts/tg4-mixer/benches/main.rs

Updates the mixing function benchmark setup / values to latest version of deps.
These are the current gas costs, by the way:
```
$ cbench --locked
...
GeometricMean(100000, 5000) = 22360 ( 42 SDK gas)
Sigmoid(100000, 5000) =  1000 (642 SDK gas)
SigmoidSqrt(100000, 5000) =   997 (147 SDK gas)
AlgebraicSigmoid(100000, 5000) =   996 (609 SDK gas)
$ 
```

Mixer mixing fn benches

---

contracts/tgrade-validator-voting/src/multitest/proposals.rs
contracts/tgrade-validator-voting/src/multitest/suite.rs
packages/bindings-test/src/multitest.rs
packages/bindings/src/gov.rs

#157 follow-up. Add multi test for change params.

Tgrade gov change params 2

---

contracts/tgrade-valset/src/contract.rs
packages/utils/src/migrate.rs

Makes `ensure_from_older_version` (which could very well be named `update_version`) return the original contract version for convenience.
This is because current migration code usually reads the contract version *after* calling this function. Which is a bug, as the contract version has already been updated (by this function) at that point.

Older version migration helper

---

contracts/tg4-engagement/src/msg.rs
contracts/tgrade-valset/src/contract.rs
contracts/tgrade-valset/src/msg.rs
contracts/tgrade-valset/src/multitest/migration.rs
contracts/tgrade-valset/src/multitest/suite.rs
contracts/tgrade-valset/src/multitest/verify_online.rs
contracts/tgrade-valset/src/state.rs

Closes #149.
This implements a hash map of signing block heights per validator, so that a lack of signing interval (1000 blocks) can be detected, and the associated validator jailed.
This gets rid of the `PENDING_VALIDATORS` list, as now validators are accepted with their full power since the beginning, and jailed if they miss signing a string of blocks.
After the jailing period expires validators are re-instated (with `auto-unjail`), but will be jailed automatically if failing to sign blocks again.
Requires https://github.com/confio/tgrade/pull/428 to work. So, this will require a chain upgrade, not only the valset contract upgrade / migration. 
TODO:
- ~~Cache validator "addresses" (SHA256-20 hashes) for performance? Would require benchmarking / comparison of reading hashes from storage …

Verify validators revisited

---

.circleci/config.yml
CHANGELOG.md
Cargo.lock
contracts/tg4-engagement/Cargo.toml
contracts/tg4-group/Cargo.toml
contracts/tg4-mixer/Cargo.toml
contracts/tg4-mixer/benches/main.rs
contracts/tg4-mixer/src/member_indexes.rs
contracts/tg4-stake/Cargo.toml
contracts/tg4-stake/src/claim.rs
contracts/tgrade-community-pool/Cargo.toml
contracts/tgrade-gov-reflect/Cargo.toml
contracts/tgrade-validator-voting/Cargo.toml
contracts/tgrade-valset/Cargo.toml
contracts/tgrade-vesting-account/Cargo.toml
packages/bindings-test/Cargo.toml
packages/bindings/Cargo.toml
packages/test-utils/Cargo.toml
packages/tg3/Cargo.toml
packages/tg4/Cargo.toml
packages/utils/Cargo.toml
packages/utils/src/member_indexes.rs
packages/voting-contract/Cargo.toml
packages/voting-contract/src/ballots.rs

Maintenance release. Just to update deps to latest cw and cw-plus versions. And sync up version numbers.
**Update**: will include required valset update / migration changes (related to #182) in this release.

Release 0.15

---

contracts/tgrade-validator-voting/src/contract.rs
contracts/tgrade-validator-voting/src/error.rs
contracts/tgrade-validator-voting/src/msg.rs
contracts/tgrade-validator-voting/src/validate.rs

Closes part of #158:
- `PromoteToPrivilegedContract`.
- `DemotePrivilegedContract`.
- `SetContractAdmin`.
- `ClearContractAdmin`.

Add promote / demote contract to privileged gov proposal

---

contracts/tg4-stake/examples/schema.rs
contracts/tg4-stake/src/contract.rs
contracts/tg4-stake/src/msg.rs

Add the ability for `migrate()` to update config values.
Needed for emergency disabling buggy `auto_return_limit`.

Add MigrateMsg with update config options

---

contracts/tg4-stake/src/claim.rs
contracts/tg4-stake/src/contract.rs

Fix claims auto-release of vesting amounts.

Fix claims auto-release of vesting amounts

---

contracts/tg4-engagement/src/contract.rs
contracts/tg4-engagement/src/msg.rs
contracts/tg4-engagement/src/multitest.rs
contracts/tg4-engagement/src/multitest/suite.rs

Add support for changing the half-life parameter through a contract migration.
This is not currently needed, but can be useful in the future. Made these changes because of some tests / checks I'm running in testnet.

Engagement half-life

---

contracts/tg4-stake/src/claim.rs
contracts/tg4-stake/src/contract.rs
contracts/tg4-stake/src/msg.rs

Needed as part of repairing the auto-release claims bug (#198).

Add undelegations processing to migration handler

---

Cargo.lock
contracts/tg4-engagement/Cargo.toml
contracts/tg4-engagement/src/contract.rs
contracts/tg4-engagement/src/lib.rs
contracts/tg4-engagement/src/migration.rs

Closes #203.
Opted for straightforward changes for the fix, instead of a full refactoring. `Member.points` is unsigned, and adding more complexity to `update_members` doesn't look like a good idea. In fact, perhaps it would be better to break down `update_members` into `add_members` and `remove_members` (as suggested in the past), and then add  a new `halve_members` in parallel.
TODO:
- ~~Unit tests~~. (done)
- ~~Migration handler update member msgs fixing code~~ (done).

Add half-life event member updates

---

CHANGELOG.md
Cargo.lock
contracts/tg4-engagement/Cargo.toml
contracts/tg4-group/Cargo.toml
contracts/tg4-mixer/Cargo.toml
contracts/tg4-stake/Cargo.toml
contracts/tgrade-community-pool/Cargo.toml
contracts/tgrade-gov-reflect/Cargo.toml
contracts/tgrade-validator-voting/Cargo.toml
contracts/tgrade-valset/Cargo.toml
contracts/tgrade-vesting-account/Cargo.toml
packages/bindings-test/Cargo.toml
packages/bindings/Cargo.toml
packages/test-utils/Cargo.toml
packages/tg3/Cargo.toml
packages/tg4/Cargo.toml
packages/utils/Cargo.toml
packages/voting-contract/Cargo.toml

Tried the `tg4-engagement` migration in the testnet, and AFAIK it worked as expected. Both mixer and distribution points were reduced after the migration.

Release 0.17.1
